server:
  port: ${epic.showcase.server.port:8080}

spring:
  datasource:
    url: ${epic.showcase.ds.url:jdbc:mysql://127.0.0.1/showcase?useUnicode=true&characterEncoding=utf8}
    username: ${epic.showcase.ds.username:public}
    password: ${epic.showcase.ds.password:public}
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: "SELECT 1"
  jpa:
    show-sql: ${epic.showcase.jpa.show-sql:true}
    database: ${epic.showcase.jpa.database:MYSQL}
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${epic.showcase.amqp.host:127.0.0.1}
    port: ${epic.showcase.amqp.port:5672}
    username: ${epic.showcase.amqp.username:guest}
    password: ${epic.showcase.amqp.password:guest}
